import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "@/components/shared/Footer";
import { NavbarComponent } from "@/components/shared/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-[#F9F2E6]`}>
        <NavbarComponent />
        {children}
        <Footer />
      </body>
    </html>
  );
}
